// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/assembly-orders": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "组装拆装单列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "库存"
                ],
                "summary": "新增组装拆装单",
                "responses": {}
            }
        },
        "/api/v1/assembly-orders/:id": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "组装拆装单详情",
                "responses": {}
            },
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "修改组装拆装单",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "库存"
                ],
                "summary": "删除组装拆装单",
                "responses": {}
            }
        },
        "/api/v1/assembly-orders/:id/complete": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "组装拆装单过账",
                "responses": {}
            }
        },
        "/api/v1/assembly-templates": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "拆装模板列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "库存"
                ],
                "summary": "新增拆装模板",
                "responses": {}
            }
        },
        "/api/v1/assembly-templates/:id": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "拆装模板详情",
                "responses": {}
            },
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "修改拆装模板",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "库存"
                ],
                "summary": "删除拆装模板",
                "responses": {}
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "使用用户名和密码登录，返回 JWT 令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "清除当前登录状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 JWT 获取登录用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.UserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "使用 RefreshToken 获取新的 AccessToken（同时轮换 RefreshToken）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "刷新访问令牌",
                "parameters": [
                    {
                        "description": "刷新参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RefreshReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/auth/wecom/config": {
            "get": {
                "description": "返回 corpid/agentId/inviteQrUrl/redirectHost 供登录页使用（不含 secret）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "企业微信登录配置",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/wecom/mp": {
            "post": {
                "description": "getPhoneNumber code → 手机号 → 校验企业成员身份 → 绑定/签发 JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "小程序企业微信登录",
                "parameters": [
                    {
                        "description": "手机号授权码",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.wecomCodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/auth/wecom/web": {
            "post": {
                "description": "WWLogin 授权 code → 成员 userid → 详情(手机号) → 绑定/签发 JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "Web 企业微信扫码登录",
                "parameters": [
                    {
                        "description": "扫码授权码",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.wecomCodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.LoginResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/base-data/delivery-methods": {
            "get": {
                "tags": [
                    "资料"
                ],
                "summary": "发货方式列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "资料"
                ],
                "summary": "新增发货方式",
                "responses": {}
            }
        },
        "/api/v1/base-data/delivery-methods/:id": {
            "put": {
                "tags": [
                    "资料"
                ],
                "summary": "修改发货方式",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "资料"
                ],
                "summary": "删除发货方式",
                "responses": {}
            }
        },
        "/api/v1/base-data/initial-accounts": {
            "get": {
                "tags": [
                    "资料"
                ],
                "summary": "现金银行期初列表",
                "responses": {}
            },
            "put": {
                "tags": [
                    "资料"
                ],
                "summary": "保存现金银行期初",
                "responses": {}
            }
        },
        "/api/v1/base-data/initial-balances": {
            "get": {
                "tags": [
                    "资料"
                ],
                "summary": "往来期初列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "customer客户 supplier供应商",
                        "name": "bizType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "tags": [
                    "资料"
                ],
                "summary": "保存往来期初",
                "responses": {}
            }
        },
        "/api/v1/base-data/initial-stocks": {
            "get": {
                "tags": [
                    "资料"
                ],
                "summary": "商品库存期初列表",
                "responses": {}
            },
            "put": {
                "tags": [
                    "资料"
                ],
                "summary": "保存商品库存期初",
                "responses": {}
            }
        },
        "/api/v1/base-data/logistics-companies": {
            "get": {
                "tags": [
                    "资料"
                ],
                "summary": "物流公司列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "资料"
                ],
                "summary": "新增物流公司",
                "responses": {}
            }
        },
        "/api/v1/base-data/logistics-companies/:id": {
            "put": {
                "tags": [
                    "资料"
                ],
                "summary": "修改物流公司",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "资料"
                ],
                "summary": "删除物流公司",
                "responses": {}
            }
        },
        "/api/v1/base-data/materials": {
            "get": {
                "tags": [
                    "资料"
                ],
                "summary": "素材库列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "资料"
                ],
                "summary": "新增素材",
                "responses": {}
            }
        },
        "/api/v1/base-data/materials/:id": {
            "delete": {
                "tags": [
                    "资料"
                ],
                "summary": "删除素材",
                "responses": {}
            }
        },
        "/api/v1/base-data/stock-op-types": {
            "get": {
                "tags": [
                    "资料"
                ],
                "summary": "出入库类型列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名称/编号",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "in入库 out出库",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "post": {
                "tags": [
                    "资料"
                ],
                "summary": "新增出入库类型",
                "responses": {}
            }
        },
        "/api/v1/base-data/stock-op-types/:id": {
            "put": {
                "tags": [
                    "资料"
                ],
                "summary": "修改出入库类型",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "资料"
                ],
                "summary": "删除出入库类型",
                "responses": {}
            }
        },
        "/api/v1/bill-center": {
            "get": {
                "tags": [
                    "单据中心"
                ],
                "summary": "单据中心统一查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "单据类型",
                        "name": "billType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "单据编号",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "往来单位",
                        "name": "counterpart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "单据状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "支付状态",
                        "name": "payStatus",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "只显示草稿单",
                        "name": "onlyDraft",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/cost-adjusts": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "成本调价单列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "单号",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "仓库",
                        "name": "warehouseId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "post": {
                "tags": [
                    "库存"
                ],
                "summary": "新增成本调价单",
                "responses": {}
            }
        },
        "/api/v1/cost-adjusts/:id": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "成本调价单详情",
                "responses": {}
            },
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "修改成本调价单",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "库存"
                ],
                "summary": "删除成本调价单",
                "responses": {}
            }
        },
        "/api/v1/cost-adjusts/:id/complete": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "成本调价单过账",
                "responses": {}
            }
        },
        "/api/v1/inventory-reports/batch-stats": {
            "get": {
                "tags": [
                    "库存报表"
                ],
                "summary": "库存批号统计",
                "responses": {}
            }
        },
        "/api/v1/inventory-reports/batch-trace": {
            "get": {
                "tags": [
                    "库存报表"
                ],
                "summary": "批号跟踪详情",
                "responses": {}
            }
        },
        "/api/v1/inventory-reports/expiry-warning": {
            "get": {
                "tags": [
                    "库存报表"
                ],
                "summary": "商品近效期预警",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "预警天数 默认90",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/inventory-reports/inout-flow": {
            "get": {
                "tags": [
                    "库存报表"
                ],
                "summary": "商品出入库流水（行级，跨单据类型）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "单据类型",
                        "name": "billType",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/inventory-reports/inout-summary": {
            "get": {
                "tags": [
                    "库存报表"
                ],
                "summary": "商品进销存汇总（期初/本期入库按单据类型/本期出库按单据类型/结存）",
                "responses": {}
            }
        },
        "/api/v1/inventory-reports/other-inout-stats": {
            "get": {
                "tags": [
                    "库存报表"
                ],
                "summary": "其他出入库统计",
                "responses": {}
            }
        },
        "/api/v1/inventory-reports/stock-distribution": {
            "get": {
                "tags": [
                    "库存报表"
                ],
                "summary": "库存分布表（各仓库数量列动态展开）",
                "responses": {}
            }
        },
        "/api/v1/inventory-reports/transfer-summary": {
            "get": {
                "tags": [
                    "库存报表"
                ],
                "summary": "调拨汇总表",
                "responses": {}
            }
        },
        "/api/v1/transfer-applies": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨申请单列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "库存"
                ],
                "summary": "新增调拨申请单",
                "responses": {}
            }
        },
        "/api/v1/transfer-applies/:id": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨申请单详情",
                "responses": {}
            },
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "修改调拨申请单",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "库存"
                ],
                "summary": "删除调拨申请单",
                "responses": {}
            }
        },
        "/api/v1/transfer-applies/:id/approve": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "审核调拨申请单",
                "responses": {}
            }
        },
        "/api/v1/transfer-diffs": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨差异处理列表",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "包含没有差异商品行",
                        "name": "includeNoDiff",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "包含未入库商品行",
                        "name": "includeNotReceived",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/transfer-diffs/:itemId/handle": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "处理调拨差异",
                "responses": {}
            }
        },
        "/api/v1/transfer-ins": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨入库单列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "库存"
                ],
                "summary": "新增调拨入库单",
                "responses": {}
            }
        },
        "/api/v1/transfer-ins/:id": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨入库单详情",
                "responses": {}
            }
        },
        "/api/v1/transfer-ins/:id/complete": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨入库单过账",
                "responses": {}
            }
        },
        "/api/v1/transfer-outs": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨出库单列表",
                "responses": {}
            },
            "post": {
                "tags": [
                    "库存"
                ],
                "summary": "新增调拨出库单",
                "responses": {}
            }
        },
        "/api/v1/transfer-outs/:id": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨出库单详情",
                "responses": {}
            },
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "修改调拨出库单",
                "responses": {}
            },
            "delete": {
                "tags": [
                    "库存"
                ],
                "summary": "删除调拨出库单",
                "responses": {}
            }
        },
        "/api/v1/transfer-outs/:id/complete": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "调拨出库单过账",
                "responses": {}
            }
        },
        "/other-in-stocks": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "其他入库单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "单号",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品名称/编号",
                        "name": "productKw",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "入库仓库",
                        "name": "warehouseId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态 draft/completed",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "入库类型",
                        "name": "inType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "录单时间起 YYYY-MM-DD",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "录单时间止 YYYY-MM-DD",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "库存"
                ],
                "summary": "新增其他入库单（草稿或保存并过账）",
                "parameters": [
                    {
                        "description": "单据内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.OtherInStockSaveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/other-in-stocks/export": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "导出其他入库单列表 Excel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "单号",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品名称/编号",
                        "name": "productKw",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "入库仓库",
                        "name": "warehouseId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态 draft/completed",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "入库类型",
                        "name": "inType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "录单时间起 YYYY-MM-DD",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "录单时间止 YYYY-MM-DD",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/other-in-stocks/export/items": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "导出其他入库单明细 Excel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "单号",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品名称/编号",
                        "name": "productKw",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "入库仓库",
                        "name": "warehouseId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态 draft/completed",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "入库类型",
                        "name": "inType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "录单时间起 YYYY-MM-DD",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "录单时间止 YYYY-MM-DD",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/other-in-stocks/import": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "库存"
                ],
                "summary": "导入其他入库单",
                "parameters": [
                    {
                        "type": "file",
                        "description": "其他入库单明细文件（.xlsx/.xls）",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "传 1 时过账单据同时增加库存（默认不写库存）",
                        "name": "applyStock",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/other-in-stocks/{id}": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "其他入库单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "单据ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "编辑其他入库单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "单据ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "单据内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.OtherInStockSaveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "库存"
                ],
                "summary": "删除其他入库单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "单据ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/other-in-stocks/{id}/complete": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "其他入库单过账",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "单据ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/other-out-stocks": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "其他出库单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "单号",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品名称/编号",
                        "name": "productKw",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "出库仓库",
                        "name": "warehouseId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态 draft/completed",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "出库类型",
                        "name": "outType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "录单时间起 YYYY-MM-DD",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "录单时间止 YYYY-MM-DD",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "库存"
                ],
                "summary": "新增其他出库单（草稿或保存并过账）",
                "parameters": [
                    {
                        "description": "单据内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.OtherOutStockSaveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/other-out-stocks/{id}": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "其他出库单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "单据ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "编辑其他出库单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "单据ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "单据内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.OtherOutStockSaveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "库存"
                ],
                "summary": "删除其他出库单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "单据ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/other-out-stocks/{id}/complete": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "其他出库单过账",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "单据ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/stocks/import": {
            "post": {
                "description": "导入老系统库存状况导出文件（.xls/.xlsx），按名称匹配/新建商品并把库存总量写入目标仓库",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "库存"
                ],
                "summary": "库存状况 Excel 导入",
                "parameters": [
                    {
                        "type": "file",
                        "description": "库存状况导出文件（.xls/.xlsx，≤10MB）",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "目标仓库ID，为空取公司第一个仓库",
                        "name": "warehouseId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/stocks/status": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "库存状况表（按商品/按分类）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品名称/编号",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "仓库ID",
                        "name": "warehouseId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "商品分类ID（含子分类）",
                        "name": "categoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "库存状态 in/out/belowMin/aboveMax",
                        "name": "stockStatus",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商品状态 1启用 0停用",
                        "name": "productStatus",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "仅显示有账面库存商品",
                        "name": "onlyWithStock",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "product 按商品 / category 按分类",
                        "name": "groupBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/stocks/status/limits": {
            "put": {
                "tags": [
                    "库存"
                ],
                "summary": "批量设置商品库存上下限",
                "parameters": [
                    {
                        "description": "商品ID列表与上下限",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.StockLimitReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/stocks/status/{productId}/flows": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "商品出入库明细",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/stocks/status/{productId}/warehouses": {
            "get": {
                "tags": [
                    "库存"
                ],
                "summary": "商品库存分布",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3
                }
            }
        },
        "handler.LoginResp": {
            "type": "object",
            "properties": {
                "accessExpiresIn": {
                    "description": "访问令牌有效期（秒）",
                    "type": "integer"
                },
                "accessToken": {
                    "type": "string"
                },
                "refreshExpiresIn": {
                    "description": "刷新令牌有效期（秒）",
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/handler.UserInfo"
                }
            }
        },
        "handler.OtherInStockItemReq": {
            "type": "object",
            "required": [
                "productId",
                "quantity"
            ],
            "properties": {
                "price": {
                    "type": "number"
                },
                "productId": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "handler.OtherInStockSaveReq": {
            "type": "object",
            "required": [
                "billDate",
                "inType",
                "items",
                "warehouseId"
            ],
            "properties": {
                "billDate": {
                    "type": "string"
                },
                "businessManagerId": {
                    "type": "integer"
                },
                "complete": {
                    "description": "true=保存并过账",
                    "type": "boolean"
                },
                "counterpart": {
                    "type": "string"
                },
                "deptId": {
                    "type": "integer"
                },
                "handlerId": {
                    "type": "integer"
                },
                "inType": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/handler.OtherInStockItemReq"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "settleUnit": {
                    "type": "string"
                },
                "warehouseId": {
                    "type": "integer"
                }
            }
        },
        "handler.OtherOutStockItemReq": {
            "type": "object",
            "required": [
                "productId",
                "quantity"
            ],
            "properties": {
                "price": {
                    "type": "number"
                },
                "productId": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "handler.OtherOutStockSaveReq": {
            "type": "object",
            "required": [
                "billDate",
                "items",
                "outType",
                "warehouseId"
            ],
            "properties": {
                "billDate": {
                    "type": "string"
                },
                "complete": {
                    "type": "boolean"
                },
                "counterpart": {
                    "type": "string"
                },
                "deptId": {
                    "type": "integer"
                },
                "handlerId": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/handler.OtherOutStockItemReq"
                    }
                },
                "outType": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "settleUnit": {
                    "type": "string"
                },
                "warehouseId": {
                    "type": "integer"
                }
            }
        },
        "handler.RefreshReq": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "handler.StockLimitReq": {
            "type": "object",
            "required": [
                "productIds"
            ],
            "properties": {
                "maxStock": {
                    "type": "number"
                },
                "minStock": {
                    "type": "number"
                },
                "productIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "handler.UserInfo": {
            "type": "object",
            "properties": {
                "deptId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "roleId": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.wecomCodeReq": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
